version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
    commands:
    - echo "Installing dependencies using Yarn..."
    - yarn install
  pre_build:
    commands:
    - echo "Pre-build steps..." 
  build:
    commands:
    - echo "Building the React and Nest.js application..."
    - yarn build
  post_build:
    commands:
    - echo "Build completed on date"
artifacts:
  files:
  - '**/*'