name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.7.0

    - name: Install dependencies
      run: npm install

    - name: Grant execute permissions for Mocha
      run: chmod +x ./node_modules/.bin/mocha

    - name: Run tests
      run: npx mocha

    - name: Start server
      run: npm start
