name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.7.0

    - name: Install dependencies
      run: npm install

    - name: Start server and run tests
      run: |
        npm start &
        SERVER_PID=$!
        # Wait for the server to start
        sleep 10
        npm test
        kill $SERVER_PID
